# Generated by Django 5.2.5 on 2025-08-28 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact', models.CharField(help_text='Email або Telegram', max_length=180)),
                ('license_type', models.CharField(choices=[('nonexclusive', 'Неексклюзив — мінус + права, трек лишається на моєму каналі'), ('exclusive', 'Ексклюзив — мінус + права, я ховаю трек у себе'), ('exclusive_stems', 'Ексклюзив+ (зі стемами) — все те ж + доріжки інструментів')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='new', max_length=20)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='tracks.track')),
            ],
        ),
    ]
