# Generated by Django 5.2.5 on 2025-08-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_genre_track_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True),
        ),
    ]
