# Generated by Django 5.2.5 on 2025-08-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_track_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
    ]
