# Generated by Django 5.2.5 on 2025-08-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_alter_track_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='order_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='license_type',
            field=models.CharField(choices=[('nonexclusive', 'Неексклюзив — мінус + права, трек лишається на моєму каналі'), ('exclusive', 'Ексклюзив — мінус + права, я ховаю трек у себе'), ('exclusive_stems', 'Ексклюзив+ (зі стемами) — все те ж + доріжки інструментів')], default='non_exclusive', max_length=32),
        ),
    ]
